# Group: Zachary Qian

**Note: I affirm that I personally wrote the text, code, and comments in this in-class assignment.**


# Discussion Activity: Ulam Spirals

An Ulam spiral is a graphical depiction of the set of prime numbers with intriguing geometrical patterns. This depiction was created by the famous mathematician Stanisław Ulam. Ulam is better known for several of his other creations, including the design of the hydrogen bomb and the Monte Carlo method for simulating complex processes. 

To create an Ulam spiral, start by arranging the integers in spiral grid: <br><br>

<figure class="image" style="width:30%">
  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Ulam_spiral_howto_all_numbers.svg/1024px-Ulam_spiral_howto_all_numbers.svg.png" alt="The integers 1 through 49 arranged in a spiral, with 1 at the center, 2 immediately to the right of 1, 3 above 2, 4 to the right of 3 (above 1), and so on.">
  <figcaption><i>Spiral arrangement of the integers. Image credit: Wikipedia.</i></figcaption>
</figure>

Then, color all the cells with prime numbers in black, and all the cells with composite numbers in white. Here's the result for a large grid: <br> <br> 

<figure class="image" style="width:50%">
  <img src="https://upload.wikimedia.org/wikipedia/commons/6/69/Ulam_1.png" alt="A 200x200 grid in which dots corresponding to prime numbers are colored black. There are several diagonal and vertical lines with high densities of black dots.">
  <figcaption><i>A 200x200 Ulam spiral. Image credit: Wikipedia.</i></figcaption>
</figure>

Note several diagonal, horizontal, and vertical lines with high densities of black dots. These geometrical structures remain only partially understood, and are connected to several important open problems in the theory of prime numbers. 

## What We'll Do

In this discussion activity, we will write a generator which supports "spiral" iteration: 

```python
for i, j, k in spiral(5):
    print(i,j,k)
    
2 2 1
3 2 2
3 1 3
2 1 4
1 1 5
#...
```
The first two numbers give the **coordinates** of a square, while the third number gives the integer corresponding to that square. For example, the number `1` corresponds to `(2,2)`, the number `4` corresponds to `(2,1)`, and so on. 

We start at `(2,2)` because this is the middle of a `5x5` grid. 

Take a moment to compare to the first diagram to convince yourself that the sample output shown above does indeed correspond to the spiral pattern shown. 

### Part (A)

Create a grid `G`, represented as a list of `n` lists, each of which contains `n` entries equal to `0`. This can be done in a single line using a double list comprehension. Start with `n = 5`. 

#### Your solution

In [26]:
#[[0 if i in range(7,20) else 0 for i in range(1,7)] j for j in range(0,6)]
G = [[0 for i in range(6)] for i in range(6)]

### Part (B)

We are now going to implement the `spiral()` generator. If you investigate the first diagram in this assignment, you'll observe that, after starting in the middle, 

1. We take **one** step right, then turn left (so now we are facing up). We take **one** step up, then turn left again (so now we are facing left). 
2. Then, we take **two** steps left, then turn left (so now we are facing down). We then take **two** steps down, then turn left (so now we are facing right). 
3. Then, we take **three** steps...

So, our approach is to implement this behavior. 

1. `spiral()` should accept a single argument `n`, an odd integer. Check that `n` is an integer, and raise a `TypeError` if not. Then, check that `n` is *odd*, and raise a `ValueError` if not. 
1. Start with a variable  `pos = (m,m)`, where `m = int((n-1)/2)` is the midpoint of the grid. Additionally, initialize a variable `k = 1` to log the current integer, and a `direction` tuple with `(0,1)` indicating the direction we are facing. Finally, initialize a `length` variable with value `1`. 
2. **Main loop:**
    1. As long as `k <= n**2 - 1`
        1. Do the following twice (that is, do i and ii, then do i and ii again). 
            1. Take a number of steps equal to `length`. In a step, we add the current `direction` to the current position `pos` entrywise. After each step, if `k <= n**2`, yield `(pos[0], pos[1], k)`, then increment `k` by one. 
            2. Change direction by making a left turn. You can do so by replacing `direction` with its value in the supplied `left_turns` dictionary. 
        2. Increment length by 1. 

This is the "main part" of the activity, so it's ok to spend some extra time here. 

#### Your solution

In [27]:
left_turns = {
        ( 1,  0) : ( 0,  1),
        ( 0,  1) : (-1,  0),
        (-1,  0) : ( 0, -1),
        ( 0, -1) : ( 1,  0)
    }

def spiral(n):
    """
    spiral() function that generates the spiraling motion for ulam spiral
    """
    
    # Step 1:
    # check that n is an integer, and raise a TypeError if not. 
    if type(n) != int:
        raise TypeError("spiral() accepts only integer parameter values.")
        
    
    # if the user supplies an even value of n, raise an informative ValueError. 
    elif n %2 == 0:
        raise ValueError("spiral() function only accepts odd integers.")
    
    
    # Step 2: 
    # initialize variables described in instructions above.
    m = int((n-1)/2)
    pos = (m,m)
    k = 1 #log current integer
    direction = (0,1)
    length = 1
    

    
    # Step 3: 
    # main loop, refer to instructions above
    while k <= n**2 - 1:
        pos += direction
        if k <= n**2:
            yield(pos[0],pos[1],k)
            k+=1
        pos += direction
        if k <= n**2:
            yield(pos[0],pos[1],k)
            k+=1
        direction = left_turns[direction]
        length +=1
    
    
    

### Part (C)

Check your code by running (`shift + enter`) the following lines. When your code is correct, you'll see a spiral from 1-25 that matches the diagram at the beginning of the activity, like this: 

```
[[17, 16, 15, 14, 13],
 [18,  5,  4,  3, 12],
 [19,  6,  1,  2, 11],
 [20,  7,  8,  9, 10],
 [21, 22, 23, 24, 25]]
```


In [28]:
for i, j, k  in spiral(11):
    G[i][j] = k
G

[[0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 120]]

### Part (D)

Here's the solution code for our prime number checker from last week. Run this code. Yes, all you need to do for this part is `shift + enter`. 

In [ ]:
import math

def create_prime_checker():
    """
    Return a function prime_checker() which takes a single argument n. 
    prime_checker() stores a list of known primes. If n is in the list of known primes, 
    then prime_checker() returns true. 
    Otherwise, prime_checker() will first check whether n is divisible by one of the known primes, returning False if so. 
    If not, prime_checker() will then check whether n is divisible by any number between the largest known prime and 
    math.sqrt(n), returning False if so. 
    If not, then n is added to the list of known primes and True is returned. 
    """
    
    d = [2]
    
    def prime_checker(n, verbose = False):
            
        # if verbose == True, print the list of known primes (this is primarily for your debugging)
        
        if n == 1:
            return False
        
        if verbose:
            print("Known primes: ", end = "")
            print(d)
        
        # first, check whether n is in the list of known primes, and act appropriately. 

        if n in d:
            return True
        
        # next, check whether any of the known primes divide n, and act appropriately. 
        
        for possible_factor in d:
            if n % possible_factor == 0:
                return False
        
        # next, check possible factors up to and include math.sqrt(n), and act appropriately. 
        # the below works because possible_factor is now a variable (because of the for-loop)
        
        while possible_factor <= math.sqrt(n):
            if n % possible_factor == 0:
                return False
            possible_factor += 1
        
        # If no factors found, add n to the list of known primes and return the appropriate value. 
        
        d.append(n)
        return True
        
    return prime_checker

### Part (E) 

Create a new grid `G` like you did in Part (A), this time using `n = 101`, and initialize a `prime_checker()` function. To do so, just do `shift + enter` on the block below. 

In [ ]:
prime_checker = create_prime_checker()

n = 101
G = [[0 for i in range(n)] for j in range(n)]

Then, iterate through the grid using the `spiral` generator. You should mark a `1` in the cell corresponding to `k` if `k` is prime. The code should look similar to the supplied code from Part (C). 

#### Your solution

In [2]:
import numpy as np
A = np.array([[9, 8, 4],
           [6, 2, 2], 
           [7, 7, 5], 
           [0, 1, 4]])



In [6]:
A[3:,]
A[:,1]
A[2,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [19]:
a = np.arange(3)
a

array([0, 1, 2])

In [20]:
a = (a + 2) - a
a

array([2, 2, 2])

In [18]:
a = np.array([2, 2, 2])
a

array([2, 2, 2])

In [14]:
a[0] += 2

a[1] += 1
a

array([2, 2, 2])

In [12]:
a[a < 2] = 2
a

array([2, 2, 2])

Finally, plot the result by running (`shift + enter`) the following code block. 

In [ ]:
plt.imshow(G, cmap = "Greys", vmin = 0)
plt.gca().axis('off')

### Part (F)

Add some further comments to your code in Part (B), and turn in the assignment.